import sys
import os

try:
    import kconfiglib
except ImportError:
    # kconfiglib not available — use existing config/autoconf.h if present
    if os.path.exists("config/autoconf.h"):
        print("kconfiglib not found, using existing config/autoconf.h")
        sys.exit(0)
    else:
        print("Error: kconfiglib not found. Please install it using 'pip install kconfiglib'")
        sys.exit(1)

def main():
    autoconf_path = os.path.join("config", "autoconf.h")
    
    # If autoconf.h already exists and is non-empty, skip regeneration.
    # This allows board-specific scripts (e.g., gen_m0plus_config.py) to
    # generate configs that override the Kconfig defaults.
    if os.path.exists(autoconf_path) and os.path.getsize(autoconf_path) > 0:
        print(f"config/autoconf.h already exists, skipping genconfig.py")
        return

    kconf = kconfiglib.Kconfig("Kconfig")
    
    # Load .config if it exists, otherwise use defaults
    if os.path.exists(".config"):
        kconf.load_config(".config")
    else:
        kconf.write_config(".config") # create default
        kconf.load_config(".config")
        
    # Generate C header
    os.makedirs("config", exist_ok=True)
    kconf.write_autoconf("config/autoconf.h")
    print("Generated config/autoconf.h")

    # Generate CMake variables
    with open("config/autoconf.cmake", "w") as f:
        f.write("# Automatically generated by genconfig.py\n")
        for sym in kconf.unique_defined_syms:
            if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
                if sym.str_value == "y":
                    f.write(f'set(CONFIG_{sym.name} "y")\n')
                elif sym.str_value == "m":
                    f.write(f'set(CONFIG_{sym.name} "m")\n')
            elif sym.type == kconfiglib.STRING:
                f.write(f'set(CONFIG_{sym.name} "{sym.str_value}")\n')
            elif sym.type in (kconfiglib.INT, kconfiglib.HEX):
                f.write(f'set(CONFIG_{sym.name} {sym.str_value})\n')
    print("Generated config/autoconf.cmake")

if __name__ == "__main__":
    main()
