/**
 * @file config.hpp
 * @brief Compile-time feature flags for February (Kconfig-style)
 */
#ifndef AURORA_FEBRUARY_CONFIG_HPP
#define AURORA_FEBRUARY_CONFIG_HPP

#ifndef FEBRUARY_ENABLE_SERVICE
#define FEBRUARY_ENABLE_SERVICE 1
#endif

#ifndef FEBRUARY_ENABLE_PLANNER
#define FEBRUARY_ENABLE_PLANNER 1
#endif

#ifndef FEBRUARY_ENABLE_SOFTBUS
#define FEBRUARY_ENABLE_SOFTBUS 1
#endif

#ifndef FEBRUARY_ENABLE_PEER_TABLE
#define FEBRUARY_ENABLE_PEER_TABLE 1
#endif

#ifndef FEBRUARY_REMOTE_YIELD_TO_LOCAL
#define FEBRUARY_REMOTE_YIELD_TO_LOCAL 1
#endif

#ifndef FEBRUARY_PLANNER_MAX_STEPS
#define FEBRUARY_PLANNER_MAX_STEPS 4
#endif

#ifndef FEBRUARY_SOFTBUS_QUEUE_DEPTH
#define FEBRUARY_SOFTBUS_QUEUE_DEPTH 8
#endif

#ifndef FEBRUARY_SOFTBUS_MAX_SESSIONS
#define FEBRUARY_SOFTBUS_MAX_SESSIONS 4
#endif

#ifndef FEBRUARY_PEER_TABLE_SIZE
#define FEBRUARY_PEER_TABLE_SIZE 4
#endif

#ifndef FEBRUARY_SERVICE_MAX_EVENTS
#define FEBRUARY_SERVICE_MAX_EVENTS 8
#endif

#ifndef FEBRUARY_SOFTBUS_PKG
#define FEBRUARY_SOFTBUS_PKG "aurora.february"
#endif

#ifndef FEBRUARY_SOFTBUS_SESSION
#define FEBRUARY_SOFTBUS_SESSION "february.intent"
#endif

#ifndef FEBRUARY_ENABLE_WORKING_MEMORY
#define FEBRUARY_ENABLE_WORKING_MEMORY 1
#endif

#ifndef FEBRUARY_ENABLE_EPISODIC_MEMORY
#define FEBRUARY_ENABLE_EPISODIC_MEMORY 1
#endif

#ifndef FEBRUARY_ENABLE_WORLD_MODEL
#define FEBRUARY_ENABLE_WORLD_MODEL 1
#endif

#ifndef FEBRUARY_WORKING_MEMORY_SLOTS
#define FEBRUARY_WORKING_MEMORY_SLOTS 64
#endif

#ifndef FEBRUARY_WORKING_MEMORY_WINDOW_MS
#define FEBRUARY_WORKING_MEMORY_WINDOW_MS 300000
#endif

#ifndef FEBRUARY_EPISODIC_MAX_HABITS
#define FEBRUARY_EPISODIC_MAX_HABITS 16
#endif

#ifndef FEBRUARY_WORLD_MODEL_SIZE
#define FEBRUARY_WORLD_MODEL_SIZE FEBRUARY_PEER_TABLE_SIZE
#endif

#endif  // AURORA_FEBRUARY_CONFIG_HPP
